### ISSUE TITLE
Ch 4 Predictions Contain Unnecessary Variable

### ISSUE THREAD

**Issue by WheaTex** [PacktPublishing/Learn-Amazon-SageMaker#2]
In Chapter 4 when running predictions for LinearLearner & XGBoost (at a minimum) the Jupyter Notebook suggests you run this codeblock.  

`xgb_predictor.content_type = 'text/csv'
xgb_predictor.serializer = sagemaker.serializers.CSVSerializer()
xgb_predictor.deserializer = sagemaker.deserializers.CSVDeserializer()

response = xgb_predictor.predict(test_sample)
print(response)`

This elicits an error: 
`AttributeError: can't set attribute`

It appears that the [insert_predictor (e.g., xbg or linearlearner)].content_type = 'text/csv' is un-necessary.  If you just remove it then the prediction will work.  Therefore, recommend removing this code line.

**Comment by juliensimon** [comment]
Correct, I'll fix it.

**Comment by juliensimon** [comment]
Fixed in chapter 4, will fix the other chapters one by one.
