### ISSUE TITLE
Chapter 6 : Blazing Text 

### ISSUE THREAD

**Issue by PacktAsh** [PacktPublishing/Learn-Amazon-SageMaker#5]
When running predictor, seeing attribute error. I saw there were similar error messages seen and I tried importing both the JSONserializer & JSONdeserializer.

bt_predictor.content_type = 'application/json'
response = bt_predictor.predict(json.dumps(payload))

**Comment by juliensimon** [comment]
Hi, which notebook is this ? The latest SDK v2 notebook is https://github.com/PacktPublishing/Learn-Amazon-SageMaker/blob/master/sdkv2/ch6/blazingtext/BlazingText%20on%20Amazon%20Reviews%20-%20Classification.ipynb and doesn't include the code above.
